# permissions for end users to view testcases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: testcase-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tofan
    app.kubernetes.io/part-of: tofan
    app.kubernetes.io/managed-by: kustomize
  name: testcase-viewer-role
rules:
- apiGroups:
  - tofan.io.tofan.io
  resources:
  - testcases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tofan.io.tofan.io
  resources:
  - testcases/status
  verbs:
  - get
