apiVersion: tofan.io.tofan.io/v1alpha1
kind: Report
metadata:
  labels:
    app.kubernetes.io/name: report
    app.kubernetes.io/instance: report-sample
    app.kubernetes.io/part-of: tofan
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tofan
  name: report-sample
spec:
  # TODO(user): Add fields here
